.dashKeyedFileBrowser_js_metadata <- function() {
deps_metadata <- list(`dash_keyed_file_browser` = structure(list(name = "dash_keyed_file_browser",
version = "0.0.1", src = list(href = NULL,
file = "deps"), meta = NULL,
script = 'dash_keyed_file_browser.min.js',
stylesheet = NULL, head = NULL, attachment = NULL, package = "dashKeyedFileBrowser",
all_files = FALSE), class = "html_dependency"),
`dash_keyed_file_browser` = structure(list(name = "dash_keyed_file_browser",
version = "0.0.1", src = list(href = NULL,
file = "deps"), meta = NULL,
script = 'dash_keyed_file_browser.min.js.map',
stylesheet = NULL, head = NULL, attachment = NULL, package = "dashKeyedFileBrowser",
all_files = FALSE, dynamic = TRUE), class = "html_dependency"),
`dash_keyed_file_browser` = structure(list(name = "dash_keyed_file_browser",
version = "0.0.1", src = list(href = NULL,
file = "deps"), meta = NULL,
script = NULL,
stylesheet = 'font-awesome.min.css', head = NULL, attachment = NULL, package = "dashKeyedFileBrowser",
all_files = FALSE), class = "html_dependency"),
`dash_keyed_file_browser` = structure(list(name = "dash_keyed_file_browser",
version = "0.0.1", src = list(href = NULL,
file = "deps"), meta = NULL,
script = NULL,
stylesheet = 'react-keyed-file-browser.css', head = NULL, attachment = NULL, package = "dashKeyedFileBrowser",
all_files = FALSE), class = "html_dependency"))
return(deps_metadata)
}
